FROM php:7.2.2-fpm
ARG arg

RUN apt-get update -y && \
    apt-get install -y libmcrypt-dev \
    openssl \
    curl \
    libcurl4-gnutls-dev \
    zlib1g-dev \
    libpng-dev \
    zip \
    unzip \
    libc6 \
    libxml2-dev \
    libxslt1-dev \
    libicu-dev

RUN cd /tmp && \
    wget https://pecl.php.net/get/swoole-4.2.9.tgz && \
    tar zxvf swoole-4.2.9.tgz && \
    cd swoole-4.2.9  && \
    phpize  && \
    ./configure  --enable-openssl && \
    make && \
    make install && \
    echo 'swoole.fast_serialize=On' >> /usr/local/etc/php/conf.d/docker-php-ext-swoole-serialize.ini \

RUN pecl install mcrypt-1.0.1

RUN docker-php-ext-install mbstring \
    zip \
    json \
    ctype \
    curl \
    soap \
    xml \
    intl \
    mbstring \
    iconv \
    bcmath

RUN docker-php-ext-enable mcrypt

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /src
COPY . /src

RUN if [ $arg -eq 1 ] ; then chown -R www-data:www-data /src \
#    && cp /app/.env.example /app/.env \
    && php /usr/bin/composer install \
    && phpdbg -qrr ./vendor/bin/phpunit --coverage-html code-coverage ; fi
