version: '3'

services:
  web:
    image: nginx:1.12
    ports:
      - "8890:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - kobol-network

  php:
    build:
      context: ./
    networks:
      - kobol-network
    volumes:
      - ./:/app

networks:
  kobol-network:
    external:
      name: kobol-network
