version: '3'

services:
  web:
    image: nginx:1.12
    ports:
      - "8890:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./
    volumes:
      - ./:/app
